USE customer_order_management;

#TASK-1  DISPLAY ALL CUSTOMERS WITH FIRST AND LAST NAMES, EMAIL, AND COUNTRY_CODE
SELECT first_name, last_name, email, country_code 
FROM customers;

#TASK-2  DISPLAY ALL CUSTOMERS WHOSE COUNTRY IS SOUTH AFRICA
SELECT * FROM customers 
WHERE country_code = '+21'; 

#TASK-3  DISPLAY ALL CUSTOMERS WHOSE COUNTRY IS INDIA
SELECT * FROM customers 
WHERE country_code = '+91';

#TASK-4  DISPLAY ALL CUSTOMERS WHOSE EMAILS ADDRESS USES GMAIL
SELECT * FROM customers
WHERE email LIKE '%@gmail.com';

#TASK-5  DISPLAY ALL CUSTOMERS WHOSE EMAILS ADDRESS USES OUTLOOK
SELECT * FROM customers
WHERE email LIKE '%@outlook.com';

#TASK-6  FIND THE CUSTOMER WHOSE SURNAME IS 'VARMA'
SELECT * FROM customers
WHERE last_name = 'varma';

#TASK-7  CUSTOMERS BORN IN THE 2004
SELECT * FROM customers
WHERE date_of_birth BETWEEN '2004-01-01' AND '2004-12-31'; 

#TASK-8  FIND CUSTOMERS WHO ARE FROM SOUTH AFRICA AND USE GMAIL
SELECT * FROM customers
WHERE country_code = '+21' AND email LIKE '%@gmail.com';
